// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v5.29.6
// source: proto/auth-service-health.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "authservicehealth";

export interface Empty {
}

export interface AuthServiceHealthCheckResponse {
  status: AuthServiceHealthCheckResponse_ServingStatus;
  details: { [key: string]: string };
}

export enum AuthServiceHealthCheckResponse_ServingStatus {
  UNKNOWN = 0,
  SERVING = 1,
  NOT_SERVING = 2,
  SERVICE_UNKNOWN = 3,
  UNRECOGNIZED = -1,
}

export interface AuthServiceHealthCheckResponse_DetailsEntry {
  key: string;
  value: string;
}

export const AUTHSERVICEHEALTH_PACKAGE_NAME = "authservicehealth";

export interface AuthServiceHealthClient {
  check(request: Empty): Observable<AuthServiceHealthCheckResponse>;

  watch(request: Empty): Observable<AuthServiceHealthCheckResponse>;
}

export interface AuthServiceHealthController {
  check(
    request: Empty,
  ):
    | Promise<AuthServiceHealthCheckResponse>
    | Observable<AuthServiceHealthCheckResponse>
    | AuthServiceHealthCheckResponse;

  watch(request: Empty): Observable<AuthServiceHealthCheckResponse>;
}

export function AuthServiceHealthControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["check", "watch"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthServiceHealth", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthServiceHealth", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_HEALTH_SERVICE_NAME = "AuthServiceHealth";

export interface AuthServiceHealthMonitorClient {
  checkLiveness(request: Empty): Observable<AuthServiceHealthCheckResponse>;

  checkReadiness(request: Empty): Observable<AuthServiceHealthCheckResponse>;
}

export interface AuthServiceHealthMonitorController {
  checkLiveness(
    request: Empty,
  ):
    | Promise<AuthServiceHealthCheckResponse>
    | Observable<AuthServiceHealthCheckResponse>
    | AuthServiceHealthCheckResponse;

  checkReadiness(
    request: Empty,
  ):
    | Promise<AuthServiceHealthCheckResponse>
    | Observable<AuthServiceHealthCheckResponse>
    | AuthServiceHealthCheckResponse;
}

export function AuthServiceHealthMonitorControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = ["checkLiveness", "checkReadiness"];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthServiceHealthMonitor", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthServiceHealthMonitor", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_HEALTH_MONITOR_SERVICE_NAME = "AuthServiceHealthMonitor";
