// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v7.34.0
// source: proto/auth-service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "authservice";

export interface BasicUserResponse {
  id: string;
  username: string;
  email: string;
}

export interface GetUserByIdRequest {
  id: string;
}

export interface Role {
  id: string;
  name: string;
  permissions: Permissions[];
}

export interface Permissions {
  action: string;
  subject: string;
  condition?: string | undefined;
}

export interface User {
  id: string;
  username: string;
  email: string;
  roles: Role[];
}

export interface Admin {
  id: string;
  userId: string;
  email: string;
  active: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
}

export interface Teacher {
  id: string;
  uniqueId: string;
  email: string;
  fullName: string;
  phoneNumber: string;
  dateOfBirth?: string | undefined;
  active: string;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export interface LoginRequest {
  usernameOrEmail: string;
  password: string;
}

export interface LoginResponse {
  accessToken: string;
  refreshToken: string;
  user?: User | undefined;
}

export interface RegisterAdminRequest {
  email: string;
  username: string;
  password: string;
  roleIds: string[];
}

export interface RegisterAdminResponse {
  admin?: Admin | undefined;
  user?: User | undefined;
}

export interface RegisterTeacherRequest {
  username: string;
  email: string;
  password: string;
  fullName: string;
  dateOfBirth: string;
  phoneNumber: string;
  profilePicture?: string | undefined;
}

export interface RegisterTeacherResponse {
  user?: User | undefined;
  teacher?: Teacher | undefined;
}

export interface ProfileRequest {
  userId: string;
}

export interface ProfileResponse {
  id: string;
  username: string;
  uniqueId: string;
  email: string;
  roles: Role[];
  fullName: string;
  active: string;
  profilePicture?: string | undefined;
  dateOfBirth?: string | undefined;
  phoneNumber?: string | undefined;
  branchId?: string | undefined;
  branchName?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  deletedAt?: string | undefined;
  userId?: string | undefined;
}

export interface CreateUserRequest {
  username: string;
  email: string;
  password: string;
  roleIds: string[];
}

export interface CreateUserResponse {
  id: string;
  username: string;
  email: string;
  active: string;
  roles: Role[];
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
}

export interface DeleteUserByIdRequest {
  id: string;
}

export interface DeleteUserByIdResponse {
  message: string;
}

export interface RequestPasswordResetRequest {
  email: string;
}

export interface RequestPasswordResetResponse {
  message: string;
  resetToken: string;
}

export interface ResetPasswordRequest {
  token: string;
  newPassword: string;
}

export interface ResetPasswordResponse {
  message: string;
}

export interface UpdateProfileRequest {
  userId: string;
  fullName?: string | undefined;
  profilePictureUrl?: string | undefined;
  bio?: string | undefined;
}

export interface ProfilePictureUploadUrlRequest {
  userId: string;
  filename: string;
  contentType: string;
}

export interface ProfilePictureUploadUrlResponse {
  uploadUrl: string;
  fields: { [key: string]: string };
  s3Key: string;
  publicUrl: string;
  expiresIn: number;
}

export interface ProfilePictureUploadUrlResponse_FieldsEntry {
  key: string;
  value: string;
}

export interface GetRolesRequest {
  name?: string | undefined;
}

export interface GetRolesResponse {
  roles: Role[];
}

export const AUTHSERVICE_PACKAGE_NAME = "authservice";

/** The AuthService defines authentication and user management operations */

export interface AuthServiceClient {
  /** Authenticates a user with username/email and password */

  login(request: LoginRequest): Observable<LoginResponse>;

  /** Registers a new admin user with specified roles */

  registerAdmin(request: RegisterAdminRequest): Observable<RegisterAdminResponse>;

  /** Registers a new teacher user with profile information */

  registerTeacher(request: RegisterTeacherRequest): Observable<RegisterTeacherResponse>;

  /** Retrieves the authenticated user's profile information */

  getMe(request: ProfileRequest): Observable<ProfileResponse>;

  /** Retrieves basic user information by user ID */

  getUserById(request: GetUserByIdRequest): Observable<BasicUserResponse>;

  /** Create a new user */

  createUser(request: CreateUserRequest): Observable<CreateUserResponse>;

  /** Delete user by ID */

  deleteUserById(request: DeleteUserByIdRequest): Observable<DeleteUserByIdResponse>;

  /** Request a password reset token for a user by email */

  requestPasswordReset(request: RequestPasswordResetRequest): Observable<RequestPasswordResetResponse>;

  /** Reset password using a valid reset token */

  resetPassword(request: ResetPasswordRequest): Observable<ResetPasswordResponse>;

  /** Update user profile (name, bio, profile picture URL) */

  updateProfile(request: UpdateProfileRequest): Observable<ProfileResponse>;

  /** Generate presigned URL for profile picture upload */

  getProfilePictureUploadUrl(request: ProfilePictureUploadUrlRequest): Observable<ProfilePictureUploadUrlResponse>;

  /** Get roles by optional name filter */

  getRoles(request: GetRolesRequest): Observable<GetRolesResponse>;
}

/** The AuthService defines authentication and user management operations */

export interface AuthServiceController {
  /** Authenticates a user with username/email and password */

  login(request: LoginRequest): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  /** Registers a new admin user with specified roles */

  registerAdmin(
    request: RegisterAdminRequest,
  ): Promise<RegisterAdminResponse> | Observable<RegisterAdminResponse> | RegisterAdminResponse;

  /** Registers a new teacher user with profile information */

  registerTeacher(
    request: RegisterTeacherRequest,
  ): Promise<RegisterTeacherResponse> | Observable<RegisterTeacherResponse> | RegisterTeacherResponse;

  /** Retrieves the authenticated user's profile information */

  getMe(request: ProfileRequest): Promise<ProfileResponse> | Observable<ProfileResponse> | ProfileResponse;

  /** Retrieves basic user information by user ID */

  getUserById(
    request: GetUserByIdRequest,
  ): Promise<BasicUserResponse> | Observable<BasicUserResponse> | BasicUserResponse;

  /** Create a new user */

  createUser(
    request: CreateUserRequest,
  ): Promise<CreateUserResponse> | Observable<CreateUserResponse> | CreateUserResponse;

  /** Delete user by ID */

  deleteUserById(
    request: DeleteUserByIdRequest,
  ): Promise<DeleteUserByIdResponse> | Observable<DeleteUserByIdResponse> | DeleteUserByIdResponse;

  /** Request a password reset token for a user by email */

  requestPasswordReset(
    request: RequestPasswordResetRequest,
  ): Promise<RequestPasswordResetResponse> | Observable<RequestPasswordResetResponse> | RequestPasswordResetResponse;

  /** Reset password using a valid reset token */

  resetPassword(
    request: ResetPasswordRequest,
  ): Promise<ResetPasswordResponse> | Observable<ResetPasswordResponse> | ResetPasswordResponse;

  /** Update user profile (name, bio, profile picture URL) */

  updateProfile(
    request: UpdateProfileRequest,
  ): Promise<ProfileResponse> | Observable<ProfileResponse> | ProfileResponse;

  /** Generate presigned URL for profile picture upload */

  getProfilePictureUploadUrl(
    request: ProfilePictureUploadUrlRequest,
  ):
    | Promise<ProfilePictureUploadUrlResponse>
    | Observable<ProfilePictureUploadUrlResponse>
    | ProfilePictureUploadUrlResponse;

  /** Get roles by optional name filter */

  getRoles(request: GetRolesRequest): Promise<GetRolesResponse> | Observable<GetRolesResponse> | GetRolesResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "login",
      "registerAdmin",
      "registerTeacher",
      "getMe",
      "getUserById",
      "createUser",
      "deleteUserById",
      "requestPasswordReset",
      "resetPassword",
      "updateProfile",
      "getProfilePictureUploadUrl",
      "getRoles",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
