// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v7.34.0
// source: proto/auth-service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "authservice";

export interface BasicUserResponse {
  id: string;
  username: string;
  email: string;
}

export interface GetUserByIdRequest {
  id: string;
}

export interface Role {
  id: string;
  name: string;
  permissions: Permissions[];
}

export interface Permissions {
  action: string;
  subject: string;
  condition?: string | undefined;
}

export interface User {
  id: string;
  username: string;
  email: string;
  roles: Role[];
}

export interface Admin {
  id: string;
  userId: string;
  email: string;
  active: string;
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
}

export interface Customer {
  id: string;
  uniqueId: string;
  email: string;
  fullName: string;
  phoneNumber: string;
  dateOfBirth?: string | undefined;
  active: string;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export interface LoginRequest {
  usernameOrEmail: string;
  password: string;
}

export interface LoginResponse {
  accessToken: string;
  refreshToken: string;
  user?: User | undefined;
}

export interface RegisterAdminRequest {
  email: string;
  username: string;
  password: string;
  roleIds: string[];
}

export interface RegisterAdminResponse {
  admin?: Admin | undefined;
  user?: User | undefined;
}

export interface RegisterCustomerRequest {
  username: string;
  email: string;
  password: string;
  fullName: string;
  dateOfBirth: string;
  phoneNumber: string;
  profilePicture?: string | undefined;
}

export interface RegisterCustomerResponse {
  user?: User | undefined;
  customer?: Customer | undefined;
}

export interface ProfileRequest {
  userId: string;
}

export interface ProfileResponse {
  id: string;
  username: string;
  uniqueId: string;
  email: string;
  roles: Role[];
  fullName: string;
  active: string;
  profilePicture?: string | undefined;
  dateOfBirth?: string | undefined;
  phoneNumber?: string | undefined;
  createdAt?: string | undefined;
  updatedAt?: string | undefined;
  deletedAt?: string | undefined;
  userId?: string | undefined;
}

export interface CreateUserRequest {
  username: string;
  email: string;
  password: string;
  roleIds: string[];
}

export interface CreateUserResponse {
  id: string;
  username: string;
  email: string;
  active: string;
  roles: Role[];
  createdAt: string;
  updatedAt: string;
  deletedAt: string;
}

export interface DeleteUserByIdRequest {
  id: string;
}

export interface DeleteUserByIdResponse {
  message: string;
}

export const AUTHSERVICE_PACKAGE_NAME = "authservice";

/** The AuthService defines authentication and user management operations */

export interface AuthServiceClient {
  /** Authenticates a user with username/email and password */

  login(request: LoginRequest): Observable<LoginResponse>;

  /** Registers a new admin user with specified roles */

  registerAdmin(request: RegisterAdminRequest): Observable<RegisterAdminResponse>;

  /** Registers a new customer user with profile information */

  registerCustomer(request: RegisterCustomerRequest): Observable<RegisterCustomerResponse>;

  /** Retrieves the authenticated user's profile information */

  getMe(request: ProfileRequest): Observable<ProfileResponse>;

  /** Retrieves basic user information by user ID */

  getUserById(request: GetUserByIdRequest): Observable<BasicUserResponse>;

  /** Create a new user */

  createUser(request: CreateUserRequest): Observable<CreateUserResponse>;

  /** Delete user by ID */

  deleteUserById(request: DeleteUserByIdRequest): Observable<DeleteUserByIdResponse>;
}

/** The AuthService defines authentication and user management operations */

export interface AuthServiceController {
  /** Authenticates a user with username/email and password */

  login(request: LoginRequest): Promise<LoginResponse> | Observable<LoginResponse> | LoginResponse;

  /** Registers a new admin user with specified roles */

  registerAdmin(
    request: RegisterAdminRequest,
  ): Promise<RegisterAdminResponse> | Observable<RegisterAdminResponse> | RegisterAdminResponse;

  /** Registers a new customer user with profile information */

  registerCustomer(
    request: RegisterCustomerRequest,
  ): Promise<RegisterCustomerResponse> | Observable<RegisterCustomerResponse> | RegisterCustomerResponse;

  /** Retrieves the authenticated user's profile information */

  getMe(request: ProfileRequest): Promise<ProfileResponse> | Observable<ProfileResponse> | ProfileResponse;

  /** Retrieves basic user information by user ID */

  getUserById(
    request: GetUserByIdRequest,
  ): Promise<BasicUserResponse> | Observable<BasicUserResponse> | BasicUserResponse;

  /** Create a new user */

  createUser(
    request: CreateUserRequest,
  ): Promise<CreateUserResponse> | Observable<CreateUserResponse> | CreateUserResponse;

  /** Delete user by ID */

  deleteUserById(
    request: DeleteUserByIdRequest,
  ): Promise<DeleteUserByIdResponse> | Observable<DeleteUserByIdResponse> | DeleteUserByIdResponse;
}

export function AuthServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "login",
      "registerAdmin",
      "registerCustomer",
      "getMe",
      "getUserById",
      "createUser",
      "deleteUserById",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("AuthService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const AUTH_SERVICE_NAME = "AuthService";
