// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v7.34.0
// source: proto/branch-service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "branchservice";

export enum Order {
  ASC = 0,
  DESC = 1,
  UNRECOGNIZED = -1,
}

export interface Filter {
  values: { [key: string]: string };
}

export interface Filter_ValuesEntry {
  key: string;
  value: string;
}

export interface PageMeta {
  page: number;
  pageSize: number;
  count: number;
  pageCount?: number | undefined;
  hasPreviousPage?: boolean | undefined;
  hasNextPage?: boolean | undefined;
}

export interface BranchTeacher {
  id: string;
  teacherId: string;
  fullName: string;
  profilePictureUrl?: string | undefined;
  joinedAt: string;
}

export interface BranchStudent {
  id: string;
  studentId: string;
  fullName: string;
  profilePictureUrl?: string | undefined;
}

export interface Branch {
  id: string;
  name: string;
  address?: string | undefined;
  phone?: string | undefined;
  adminId: string;
  adminName: string;
  teacherCount: number;
  studentCount: number;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
  teachers: BranchTeacher[];
  students: BranchStudent[];
}

export interface CreateBranchRequest {
  name: string;
  address?: string | undefined;
  phone?: string | undefined;
  adminId: string;
  adminName: string;
}

export interface CreateBranchResponse {
  branch?: Branch | undefined;
}

export interface GetBranchByIdRequest {
  id: string;
}

export interface GetBranchByIdResponse {
  branch?: Branch | undefined;
}

export interface UpdateBranchRequest {
  id: string;
  name?: string | undefined;
  address?: string | undefined;
  phone?: string | undefined;
  adminId?: string | undefined;
  adminName?: string | undefined;
}

export interface UpdateBranchResponse {
  branch?: Branch | undefined;
}

export interface DeleteBranchRequest {
  id: string;
}

export interface DeleteBranchResponse {
  message: string;
}

export interface GetAllBranchesRequest {
  page?: number | undefined;
  pageSize?: number | undefined;
  sortBy?: string | undefined;
  order?: Order | undefined;
  filter?: Filter | undefined;
  search?: string | undefined;
}

export interface GetAllBranchesResponse {
  branches: Branch[];
  meta?: PageMeta | undefined;
}

export interface AssignTeacherToBranchRequest {
  branchId: string;
  teacherIds: string[];
}

export interface AssignTeacherToBranchResponse {
  message: string;
  addedCount: number;
}

export interface UnassignTeacherFromBranchRequest {
  branchId: string;
  teacherId: string;
}

export interface UnassignTeacherFromBranchResponse {
  message: string;
}

export interface GetBranchTeachersRequest {
  branchId: string;
  page?: number | undefined;
  pageSize?: number | undefined;
  search?: string | undefined;
}

export interface GetBranchTeachersResponse {
  teachers: BranchTeacher[];
  meta?: PageMeta | undefined;
}

export interface AssignStudentToBranchRequest {
  branchId: string;
  studentIds: string[];
}

export interface AssignStudentToBranchResponse {
  message: string;
  addedCount: number;
}

export interface UnassignStudentFromBranchRequest {
  branchId: string;
  studentId: string;
}

export interface UnassignStudentFromBranchResponse {
  message: string;
}

export interface GetBranchStudentsRequest {
  branchId: string;
  page?: number | undefined;
  pageSize?: number | undefined;
  search?: string | undefined;
}

export interface GetBranchStudentsResponse {
  students: BranchStudent[];
  meta?: PageMeta | undefined;
}

export const BRANCHSERVICE_PACKAGE_NAME = "branchservice";

export interface BranchServiceClient {
  /** Branch CRUD */

  createBranch(request: CreateBranchRequest): Observable<CreateBranchResponse>;

  getBranchById(request: GetBranchByIdRequest): Observable<GetBranchByIdResponse>;

  updateBranch(request: UpdateBranchRequest): Observable<UpdateBranchResponse>;

  deleteBranch(request: DeleteBranchRequest): Observable<DeleteBranchResponse>;

  getAllBranches(request: GetAllBranchesRequest): Observable<GetAllBranchesResponse>;

  /** Teacher membership */

  assignTeacherToBranch(request: AssignTeacherToBranchRequest): Observable<AssignTeacherToBranchResponse>;

  unassignTeacherFromBranch(request: UnassignTeacherFromBranchRequest): Observable<UnassignTeacherFromBranchResponse>;

  getBranchTeachers(request: GetBranchTeachersRequest): Observable<GetBranchTeachersResponse>;

  /** Student membership */

  assignStudentToBranch(request: AssignStudentToBranchRequest): Observable<AssignStudentToBranchResponse>;

  unassignStudentFromBranch(request: UnassignStudentFromBranchRequest): Observable<UnassignStudentFromBranchResponse>;

  getBranchStudents(request: GetBranchStudentsRequest): Observable<GetBranchStudentsResponse>;
}

export interface BranchServiceController {
  /** Branch CRUD */

  createBranch(
    request: CreateBranchRequest,
  ): Promise<CreateBranchResponse> | Observable<CreateBranchResponse> | CreateBranchResponse;

  getBranchById(
    request: GetBranchByIdRequest,
  ): Promise<GetBranchByIdResponse> | Observable<GetBranchByIdResponse> | GetBranchByIdResponse;

  updateBranch(
    request: UpdateBranchRequest,
  ): Promise<UpdateBranchResponse> | Observable<UpdateBranchResponse> | UpdateBranchResponse;

  deleteBranch(
    request: DeleteBranchRequest,
  ): Promise<DeleteBranchResponse> | Observable<DeleteBranchResponse> | DeleteBranchResponse;

  getAllBranches(
    request: GetAllBranchesRequest,
  ): Promise<GetAllBranchesResponse> | Observable<GetAllBranchesResponse> | GetAllBranchesResponse;

  /** Teacher membership */

  assignTeacherToBranch(
    request: AssignTeacherToBranchRequest,
  ): Promise<AssignTeacherToBranchResponse> | Observable<AssignTeacherToBranchResponse> | AssignTeacherToBranchResponse;

  unassignTeacherFromBranch(
    request: UnassignTeacherFromBranchRequest,
  ):
    | Promise<UnassignTeacherFromBranchResponse>
    | Observable<UnassignTeacherFromBranchResponse>
    | UnassignTeacherFromBranchResponse;

  getBranchTeachers(
    request: GetBranchTeachersRequest,
  ): Promise<GetBranchTeachersResponse> | Observable<GetBranchTeachersResponse> | GetBranchTeachersResponse;

  /** Student membership */

  assignStudentToBranch(
    request: AssignStudentToBranchRequest,
  ): Promise<AssignStudentToBranchResponse> | Observable<AssignStudentToBranchResponse> | AssignStudentToBranchResponse;

  unassignStudentFromBranch(
    request: UnassignStudentFromBranchRequest,
  ):
    | Promise<UnassignStudentFromBranchResponse>
    | Observable<UnassignStudentFromBranchResponse>
    | UnassignStudentFromBranchResponse;

  getBranchStudents(
    request: GetBranchStudentsRequest,
  ): Promise<GetBranchStudentsResponse> | Observable<GetBranchStudentsResponse> | GetBranchStudentsResponse;
}

export function BranchServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createBranch",
      "getBranchById",
      "updateBranch",
      "deleteBranch",
      "getAllBranches",
      "assignTeacherToBranch",
      "unassignTeacherFromBranch",
      "getBranchTeachers",
      "assignStudentToBranch",
      "unassignStudentFromBranch",
      "getBranchStudents",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("BranchService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("BranchService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const BRANCH_SERVICE_NAME = "BranchService";
