// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v7.34.0
// source: proto/class-service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "classservice";

export enum Order {
  ASC = 0,
  DESC = 1,
  UNRECOGNIZED = -1,
}

export interface Filter {
  values: { [key: string]: string };
}

export interface Filter_ValuesEntry {
  key: string;
  value: string;
}

export interface PageMeta {
  page: number;
  pageSize: number;
  count: number;
  pageCount?: number | undefined;
  hasPreviousPage?: boolean | undefined;
  hasNextPage?: boolean | undefined;
}

export interface ClassTeacher {
  id: string;
  teacherId: string;
  fullName: string;
  profilePictureUrl?: string | undefined;
  joinedAt: string;
}

export interface ClassStudent {
  id: string;
  studentId: string;
  fullName: string;
  profilePictureUrl?: string | undefined;
  joinedAt: string;
}

export interface Class {
  id: string;
  uniqueId: string;
  createdBy: string;
  name: string;
  description?: string | undefined;
  active: string;
  teacherCount: number;
  studentCount: number;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
  teachers: ClassTeacher[];
  students: ClassStudent[];
}

export interface CreateClassRequest {
  createdBy: string;
  name: string;
  description?: string | undefined;
}

export interface CreateClassResponse {
  class?: Class | undefined;
}

export interface GetClassByIdRequest {
  id: string;
}

export interface GetClassByIdResponse {
  class?: Class | undefined;
}

export interface UpdateClassRequest {
  id: string;
  name?: string | undefined;
  description?: string | undefined;
  active?: string | undefined;
}

export interface UpdateClassResponse {
  class?: Class | undefined;
}

export interface DeleteClassRequest {
  id: string;
}

export interface DeleteClassResponse {
  message: string;
}

export interface GetAllClassesRequest {
  page?: number | undefined;
  pageSize?: number | undefined;
  sortBy?: string | undefined;
  order?: Order | undefined;
  filter?: Filter | undefined;
  teacherId?: string | undefined;
  search?: string | undefined;
}

export interface GetAllClassesResponse {
  classes: Class[];
  meta?: PageMeta | undefined;
}

export interface AddTeacherToClassRequest {
  classId: string;
  teacherIds: string[];
}

export interface AddTeacherToClassResponse {
  message: string;
  addedCount: number;
}

export interface RemoveTeacherFromClassRequest {
  classId: string;
  teacherId: string;
}

export interface RemoveTeacherFromClassResponse {
  message: string;
}

export interface GetClassTeachersRequest {
  classId: string;
  page?: number | undefined;
  pageSize?: number | undefined;
  search?: string | undefined;
}

export interface GetClassTeachersResponse {
  teachers: ClassTeacher[];
  meta?: PageMeta | undefined;
}

export interface AddStudentToClassRequest {
  classId: string;
  studentIds: string[];
}

export interface AddStudentToClassResponse {
  message: string;
  addedCount: number;
}

export interface RemoveStudentFromClassRequest {
  classId: string;
  studentId: string;
}

export interface RemoveStudentFromClassResponse {
  message: string;
}

export interface GetClassStudentsRequest {
  classId: string;
  page?: number | undefined;
  pageSize?: number | undefined;
  search?: string | undefined;
}

export interface GetClassStudentsResponse {
  students: ClassStudent[];
  meta?: PageMeta | undefined;
}

export interface GetStudentClassesRequest {
  studentId: string;
}

export interface GetStudentClassesResponse {
  classes: Class[];
}

export const CLASSSERVICE_PACKAGE_NAME = "classservice";

export interface ClassServiceClient {
  /** Class CRUD */

  createClass(request: CreateClassRequest): Observable<CreateClassResponse>;

  getClassById(request: GetClassByIdRequest): Observable<GetClassByIdResponse>;

  updateClass(request: UpdateClassRequest): Observable<UpdateClassResponse>;

  deleteClass(request: DeleteClassRequest): Observable<DeleteClassResponse>;

  getAllClasses(request: GetAllClassesRequest): Observable<GetAllClassesResponse>;

  /** Teacher membership */

  addTeacherToClass(request: AddTeacherToClassRequest): Observable<AddTeacherToClassResponse>;

  removeTeacherFromClass(request: RemoveTeacherFromClassRequest): Observable<RemoveTeacherFromClassResponse>;

  getClassTeachers(request: GetClassTeachersRequest): Observable<GetClassTeachersResponse>;

  /** Student membership */

  addStudentToClass(request: AddStudentToClassRequest): Observable<AddStudentToClassResponse>;

  removeStudentFromClass(request: RemoveStudentFromClassRequest): Observable<RemoveStudentFromClassResponse>;

  getClassStudents(request: GetClassStudentsRequest): Observable<GetClassStudentsResponse>;

  getStudentClasses(request: GetStudentClassesRequest): Observable<GetStudentClassesResponse>;
}

export interface ClassServiceController {
  /** Class CRUD */

  createClass(
    request: CreateClassRequest,
  ): Promise<CreateClassResponse> | Observable<CreateClassResponse> | CreateClassResponse;

  getClassById(
    request: GetClassByIdRequest,
  ): Promise<GetClassByIdResponse> | Observable<GetClassByIdResponse> | GetClassByIdResponse;

  updateClass(
    request: UpdateClassRequest,
  ): Promise<UpdateClassResponse> | Observable<UpdateClassResponse> | UpdateClassResponse;

  deleteClass(
    request: DeleteClassRequest,
  ): Promise<DeleteClassResponse> | Observable<DeleteClassResponse> | DeleteClassResponse;

  getAllClasses(
    request: GetAllClassesRequest,
  ): Promise<GetAllClassesResponse> | Observable<GetAllClassesResponse> | GetAllClassesResponse;

  /** Teacher membership */

  addTeacherToClass(
    request: AddTeacherToClassRequest,
  ): Promise<AddTeacherToClassResponse> | Observable<AddTeacherToClassResponse> | AddTeacherToClassResponse;

  removeTeacherFromClass(
    request: RemoveTeacherFromClassRequest,
  ):
    | Promise<RemoveTeacherFromClassResponse>
    | Observable<RemoveTeacherFromClassResponse>
    | RemoveTeacherFromClassResponse;

  getClassTeachers(
    request: GetClassTeachersRequest,
  ): Promise<GetClassTeachersResponse> | Observable<GetClassTeachersResponse> | GetClassTeachersResponse;

  /** Student membership */

  addStudentToClass(
    request: AddStudentToClassRequest,
  ): Promise<AddStudentToClassResponse> | Observable<AddStudentToClassResponse> | AddStudentToClassResponse;

  removeStudentFromClass(
    request: RemoveStudentFromClassRequest,
  ):
    | Promise<RemoveStudentFromClassResponse>
    | Observable<RemoveStudentFromClassResponse>
    | RemoveStudentFromClassResponse;

  getClassStudents(
    request: GetClassStudentsRequest,
  ): Promise<GetClassStudentsResponse> | Observable<GetClassStudentsResponse> | GetClassStudentsResponse;

  getStudentClasses(
    request: GetStudentClassesRequest,
  ): Promise<GetStudentClassesResponse> | Observable<GetStudentClassesResponse> | GetStudentClassesResponse;
}

export function ClassServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createClass",
      "getClassById",
      "updateClass",
      "deleteClass",
      "getAllClasses",
      "addTeacherToClass",
      "removeTeacherFromClass",
      "getClassTeachers",
      "addStudentToClass",
      "removeStudentFromClass",
      "getClassStudents",
      "getStudentClasses",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ClassService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ClassService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CLASS_SERVICE_NAME = "ClassService";
