// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.4
// source: proto/content-service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "contentservice";

export enum Order {
  ASC = 0,
  DESC = 1,
  UNRECOGNIZED = -1,
}

export enum ContentStatus {
  DRAFT = 0,
  PUBLISHED = 1,
  ARCHIVED = 2,
  UNRECOGNIZED = -1,
}

export enum MediaType {
  IMAGE = 0,
  VIDEO = 1,
  UNRECOGNIZED = -1,
}

export enum MediaProcessingStatus {
  PENDING = 0,
  PROCESSING = 1,
  COMPLETED = 2,
  FAILED = 3,
  UNRECOGNIZED = -1,
}

export interface PageMeta {
  page: number;
  pageSize: number;
  count: number;
  pageCount?: number | undefined;
  hasPreviousPage?: boolean | undefined;
  hasNextPage?: boolean | undefined;
}

export interface ContentMedia {
  id: string;
  contentId: string;
  content: Content | undefined;
  mediaType: MediaType;
  originalUrl: string;
  hlsUrl?: string | undefined;
  thumbnailUrl: string;
  bucketName: string;
  objectPath: string;
  fileName: string;
  fileSize: number;
  mimeType: string;
  duration: number;
  width: number;
  height: number;
  processingStatus: MediaProcessingStatus;
  processedAt?: string | undefined;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export interface Content {
  id: string;
  userId: string;
  title: string;
  body: string;
  status: ContentStatus;
  publishedAt?: string | undefined;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export interface GetAllContentsRequest {
  page?: number | undefined;
  pageSize?: number | undefined;
  search?: string | undefined;
  status?: ContentStatus | undefined;
  sortBy?: string | undefined;
  order?: Order | undefined;
}

export interface GetAllContentsResponse {
  contents: Content[];
  pageMeta: PageMeta | undefined;
}

export interface CreateContentRequest {
  userId: string;
  title: string;
  body: string;
  status: ContentStatus;
  media: ContentMedia[];
}

export interface CreateContentResponse {
  content: Content | undefined;
}

export interface GetContentByIdRequest {
  id: string;
}

export interface GetContentByIdResponse {
  content: Content | undefined;
  media: ContentMedia[];
}

export interface UpdateContentRequest {
  id: string;
  title?: string | undefined;
  body?: string | undefined;
  status?: ContentStatus | undefined;
  media: ContentMedia[];
}

export interface UpdateContentResponse {
  content: Content | undefined;
}

export interface DeleteContentRequest {
  id: string;
}

export interface DeleteContentResponse {
  message: string;
}

export const CONTENTSERVICE_PACKAGE_NAME = "contentservice";

/** Content Service Definition */

export interface ContentServiceClient {
  /** Content CRUD Operations */

  createContent(request: CreateContentRequest): Observable<CreateContentResponse>;

  /** Retrieve content by its unique ID */

  getContentById(request: GetContentByIdRequest): Observable<GetContentByIdResponse>;

  /** Update existing content information */

  updateContent(request: UpdateContentRequest): Observable<UpdateContentResponse>;

  /** Delete content by its unique ID */

  deleteContent(request: DeleteContentRequest): Observable<DeleteContentResponse>;

  /** Retrieve all contents with optional pagination, filtering, and sorting */

  getAllContents(request: GetAllContentsRequest): Observable<GetAllContentsResponse>;
}

/** Content Service Definition */

export interface ContentServiceController {
  /** Content CRUD Operations */

  createContent(
    request: CreateContentRequest,
  ): Promise<CreateContentResponse> | Observable<CreateContentResponse> | CreateContentResponse;

  /** Retrieve content by its unique ID */

  getContentById(
    request: GetContentByIdRequest,
  ): Promise<GetContentByIdResponse> | Observable<GetContentByIdResponse> | GetContentByIdResponse;

  /** Update existing content information */

  updateContent(
    request: UpdateContentRequest,
  ): Promise<UpdateContentResponse> | Observable<UpdateContentResponse> | UpdateContentResponse;

  /** Delete content by its unique ID */

  deleteContent(
    request: DeleteContentRequest,
  ): Promise<DeleteContentResponse> | Observable<DeleteContentResponse> | DeleteContentResponse;

  /** Retrieve all contents with optional pagination, filtering, and sorting */

  getAllContents(
    request: GetAllContentsRequest,
  ): Promise<GetAllContentsResponse> | Observable<GetAllContentsResponse> | GetAllContentsResponse;
}

export function ContentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createContent",
      "getContentById",
      "updateContent",
      "deleteContent",
      "getAllContents",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ContentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ContentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CONTENT_SERVICE_NAME = "ContentService";
