// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v7.34.0
// source: proto/content-service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "contentservice";

export enum Order {
  ASC = 0,
  DESC = 1,
  UNRECOGNIZED = -1,
}

export enum ContentStatus {
  DRAFT = 0,
  PUBLISHED = 1,
  ARCHIVED = 2,
  WAITING_FOR_REVIEW = 3,
  UNRECOGNIZED = -1,
}

export enum MediaType {
  IMAGE = 0,
  VIDEO = 1,
  DOCUMENT = 2,
  UNRECOGNIZED = -1,
}

export enum MediaProcessingStatus {
  PENDING = 0,
  PROCESSING = 1,
  COMPLETED = 2,
  FAILED = 3,
  UNRECOGNIZED = -1,
}

export interface PageMeta {
  page: number;
  pageSize: number;
  count: number;
  pageCount?: number | undefined;
  hasPreviousPage?: boolean | undefined;
  hasNextPage?: boolean | undefined;
}

export interface ContentMedia {
  id: string;
  contentId: string;
  content?: Content | undefined;
  mediaType: MediaType;
  originalUrl: string;
  hlsUrl?: string | undefined;
  thumbnailUrl: string;
  bucketName: string;
  objectPath: string;
  fileName: string;
  fileSize: number;
  mimeType: string;
  sectionId: number;
  duration: number;
  width: number;
  height: number;
  processingStatus: MediaProcessingStatus;
  processedAt?: string | undefined;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
  downloadUrl?: string | undefined;
}

export interface ContentSection {
  id: string;
  contentId: string;
  content?: Content | undefined;
  title: string;
  description?: string | undefined;
  sortOrder: number;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
  medias: ContentMedia[];
}

export interface Category {
  id: string;
  name: string;
  description?: string | undefined;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
  contents: Content[];
}

export interface Content {
  id: string;
  userId: string;
  title: string;
  body: string;
  year: number;
  categoryId: string;
  status: ContentStatus;
  publishedAt?: string | undefined;
  contentMedias: ContentMedia[];
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
  thumbnailUrl?: string | undefined;
  previewUrl?: string | undefined;
  sections: ContentSection[];
  category?: Category | undefined;
}

export interface GetAllContentsRequest {
  page?: number | undefined;
  pageSize?: number | undefined;
  search?: string | undefined;
  categoryId?: string | undefined;
  year?: number | undefined;
  status?: ContentStatus | undefined;
  sortBy?: string | undefined;
  order?: Order | undefined;
}

export interface GetAllContentsResponse {
  contents: Content[];
  pageMeta?: PageMeta | undefined;
}

export interface CreateContentRequest {
  userId: string;
  title: string;
  categoryId: string;
  year: number;
  body: string;
  status: ContentStatus;
  media: ContentMedia[];
}

export interface CreateContentResponse {
  content?: Content | undefined;
}

export interface GetContentByIdRequest {
  id: string;
}

export interface GetContentByIdResponse {
  content?: Content | undefined;
  media: ContentMedia[];
}

export interface UpdateContentRequest {
  id: string;
  title?: string | undefined;
  body?: string | undefined;
  year?: number | undefined;
  categoryId?: string | undefined;
  status?: ContentStatus | undefined;
  media: ContentMedia[];
}

export interface UpdateContentResponse {
  content?: Content | undefined;
}

export interface DeleteContentRequest {
  id: string;
}

export interface DeleteContentResponse {
  message: string;
}

export interface CreateSectionVideoInput {
  title: string;
  sortOrder: number;
  fileName: string;
  mimeType: string;
  fileSize: number;
}

export interface CreateSectionDocumentInput {
  title: string;
  sortOrder: number;
  fileName: string;
  mimeType: string;
  fileSize: number;
}

export interface CreateSectionInput {
  title: string;
  description?: string | undefined;
  sortOrder: number;
  videos: CreateSectionVideoInput[];
  documents: CreateSectionDocumentInput[];
}

export interface ThumbnailInput {
  fileName: string;
  mimeType: string;
  fileSize: number;
}

export interface PreviewVideoInput {
  fileName: string;
  mimeType: string;
  fileSize: number;
}

export interface CreateContentWithSectionsRequest {
  userId: string;
  title: string;
  categoryId: string;
  year: number;
  body: string;
  status: ContentStatus;
  sections: CreateSectionInput[];
  thumbnail?: ThumbnailInput | undefined;
  previewVideo?: PreviewVideoInput | undefined;
}

export interface UploadUrlInfo {
  mediaId: string;
  uploadUrl: string;
  fields: { [key: string]: string };
  s3Key: string;
  expiresIn: number;
}

export interface UploadUrlInfo_FieldsEntry {
  key: string;
  value: string;
}

export interface CreateContentWithSectionsResponse {
  content?: Content | undefined;
  sections: ContentSection[];
  uploadUrls: UploadUrlInfo[];
  thumbnailUploadUrl?: UploadUrlInfo | undefined;
  previewUploadUrl?: UploadUrlInfo | undefined;
  documentUploadUrls: UploadUrlInfo[];
}

export interface StartContentConversionRequest {
  contentId: string;
  callbackUrl?: string | undefined;
}

export interface ConversionJobInfo {
  mediaId: string;
  jobId: string;
}

export interface StartContentConversionResponse {
  jobs: ConversionJobInfo[];
}

export interface ConversionWebhookRequest {
  jobId: string;
  status: string;
  masterPlaylistUrl?: string | undefined;
  errorMessage?: string | undefined;
}

export interface ConversionWebhookResponse {
  success: boolean;
}

export interface GetAllCategoriesRequest {
}

export interface GetAllCategoriesResponse {
  categories: Category[];
}

export const CONTENTSERVICE_PACKAGE_NAME = "contentservice";

/** Content Service Definition */

export interface ContentServiceClient {
  /** Content CRUD Operations */

  createContent(request: CreateContentRequest): Observable<CreateContentResponse>;

  /** Create content with sections and video slots (two-phase upload) */

  createContentWithSections(request: CreateContentWithSectionsRequest): Observable<CreateContentWithSectionsResponse>;

  /** Trigger HLS conversion for all pending videos in a content */

  startContentConversion(request: StartContentConversionRequest): Observable<StartContentConversionResponse>;

  /** Handle HLS conversion webhook callback */

  handleConversionWebhook(request: ConversionWebhookRequest): Observable<ConversionWebhookResponse>;

  /** Retrieve content by its unique ID */

  getContentById(request: GetContentByIdRequest): Observable<GetContentByIdResponse>;

  /** Update existing content information */

  updateContent(request: UpdateContentRequest): Observable<UpdateContentResponse>;

  /** Delete content by its unique ID */

  deleteContent(request: DeleteContentRequest): Observable<DeleteContentResponse>;

  /** Retrieve all contents with optional pagination, filtering, and sorting */

  getAllContents(request: GetAllContentsRequest): Observable<GetAllContentsResponse>;

  /** Retrieve all categories */

  getAllCategories(request: GetAllCategoriesRequest): Observable<GetAllCategoriesResponse>;
}

/** Content Service Definition */

export interface ContentServiceController {
  /** Content CRUD Operations */

  createContent(
    request: CreateContentRequest,
  ): Promise<CreateContentResponse> | Observable<CreateContentResponse> | CreateContentResponse;

  /** Create content with sections and video slots (two-phase upload) */

  createContentWithSections(
    request: CreateContentWithSectionsRequest,
  ):
    | Promise<CreateContentWithSectionsResponse>
    | Observable<CreateContentWithSectionsResponse>
    | CreateContentWithSectionsResponse;

  /** Trigger HLS conversion for all pending videos in a content */

  startContentConversion(
    request: StartContentConversionRequest,
  ):
    | Promise<StartContentConversionResponse>
    | Observable<StartContentConversionResponse>
    | StartContentConversionResponse;

  /** Handle HLS conversion webhook callback */

  handleConversionWebhook(
    request: ConversionWebhookRequest,
  ): Promise<ConversionWebhookResponse> | Observable<ConversionWebhookResponse> | ConversionWebhookResponse;

  /** Retrieve content by its unique ID */

  getContentById(
    request: GetContentByIdRequest,
  ): Promise<GetContentByIdResponse> | Observable<GetContentByIdResponse> | GetContentByIdResponse;

  /** Update existing content information */

  updateContent(
    request: UpdateContentRequest,
  ): Promise<UpdateContentResponse> | Observable<UpdateContentResponse> | UpdateContentResponse;

  /** Delete content by its unique ID */

  deleteContent(
    request: DeleteContentRequest,
  ): Promise<DeleteContentResponse> | Observable<DeleteContentResponse> | DeleteContentResponse;

  /** Retrieve all contents with optional pagination, filtering, and sorting */

  getAllContents(
    request: GetAllContentsRequest,
  ): Promise<GetAllContentsResponse> | Observable<GetAllContentsResponse> | GetAllContentsResponse;

  /** Retrieve all categories */

  getAllCategories(
    request: GetAllCategoriesRequest,
  ): Promise<GetAllCategoriesResponse> | Observable<GetAllCategoriesResponse> | GetAllCategoriesResponse;
}

export function ContentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createContent",
      "createContentWithSections",
      "startContentConversion",
      "handleConversionWebhook",
      "getContentById",
      "updateContent",
      "deleteContent",
      "getAllContents",
      "getAllCategories",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("ContentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("ContentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CONTENT_SERVICE_NAME = "ContentService";
