// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v5.29.6
// source: proto/customer-service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "customerservice";

export enum Order {
  ASC = 0,
  DESC = 1,
  UNRECOGNIZED = -1,
}

export interface Filter {
  values: { [key: string]: string };
}

export interface Filter_ValuesEntry {
  key: string;
  value: string;
}

export interface PageMeta {
  page: number;
  pageSize: number;
  count: number;
  pageCount?: number | undefined;
  hasPreviousPage?: boolean | undefined;
  hasNextPage?: boolean | undefined;
}

export interface Role {
  id: string;
  name: string;
  permissions: string[];
}

export interface User {
  id: string;
  username: string;
  email: string;
  roles: Role[];
}

export interface Customer {
  id: string;
  uniqueId: string;
  fullName: string;
  phoneNumber: string;
  dateOfBirth?: string | undefined;
  user?: User | undefined;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export interface CreateCustomerRequest {
  userId: string;
  fullName: string;
  phoneNumber: string;
  dateOfBirth?: string | undefined;
}

export interface CreateCustomerResponse {
  customer?: Customer | undefined;
}

export interface GetCustomerByIdRequest {
  id: string;
}

export interface GetCustomerByIdResponse {
  customer?: Customer | undefined;
}

export interface UpdateCustomerRequest {
  id: string;
  fullName?: string | undefined;
  phoneNumber?: string | undefined;
  dateOfBirth?: string | undefined;
}

export interface UpdateCustomerResponse {
  customer?: Customer | undefined;
}

export interface DeleteCustomerRequest {
  id: string;
}

export interface DeleteCustomerResponse {
  message: string;
}

export interface GetAllCustomersRequest {
  page?: number | undefined;
  pageSize?: number | undefined;
  order?: Order | undefined;
  skip?: number | undefined;
  filter?: Filter | undefined;
  sortBy?: string | undefined;
  query?: string | undefined;
  search?: string | undefined;
}

export interface GetAllCustomersResponse {
  customers: Customer[];
  meta?: PageMeta | undefined;
}

export const CUSTOMERSERVICE_PACKAGE_NAME = "customerservice";

/** Customer Service Definition */

export interface CustomerServiceClient {
  /** Customer CRUD Operations */

  createCustomer(request: CreateCustomerRequest): Observable<CreateCustomerResponse>;

  /** Retrieve a customer by their unique ID */

  getCustomerById(request: GetCustomerByIdRequest): Observable<GetCustomerByIdResponse>;

  /** Update an existing customer's information */

  updateCustomer(request: UpdateCustomerRequest): Observable<UpdateCustomerResponse>;

  /** Delete a customer by their unique ID */

  deleteCustomer(request: DeleteCustomerRequest): Observable<DeleteCustomerResponse>;

  /** Retrieve all customers with optional pagination, filtering, and sorting */

  getAllCustomers(request: GetAllCustomersRequest): Observable<GetAllCustomersResponse>;
}

/** Customer Service Definition */

export interface CustomerServiceController {
  /** Customer CRUD Operations */

  createCustomer(
    request: CreateCustomerRequest,
  ): Promise<CreateCustomerResponse> | Observable<CreateCustomerResponse> | CreateCustomerResponse;

  /** Retrieve a customer by their unique ID */

  getCustomerById(
    request: GetCustomerByIdRequest,
  ): Promise<GetCustomerByIdResponse> | Observable<GetCustomerByIdResponse> | GetCustomerByIdResponse;

  /** Update an existing customer's information */

  updateCustomer(
    request: UpdateCustomerRequest,
  ): Promise<UpdateCustomerResponse> | Observable<UpdateCustomerResponse> | UpdateCustomerResponse;

  /** Delete a customer by their unique ID */

  deleteCustomer(
    request: DeleteCustomerRequest,
  ): Promise<DeleteCustomerResponse> | Observable<DeleteCustomerResponse> | DeleteCustomerResponse;

  /** Retrieve all customers with optional pagination, filtering, and sorting */

  getAllCustomers(
    request: GetAllCustomersRequest,
  ): Promise<GetAllCustomersResponse> | Observable<GetAllCustomersResponse> | GetAllCustomersResponse;
}

export function CustomerServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createCustomer",
      "getCustomerById",
      "updateCustomer",
      "deleteCustomer",
      "getAllCustomers",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("CustomerService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("CustomerService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const CUSTOMER_SERVICE_NAME = "CustomerService";
