// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v7.34.0
// source: proto/quiz-service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "quizservice";

export enum Order {
  ASC = 0,
  DESC = 1,
  UNRECOGNIZED = -1,
}

export enum QuestionType {
  MULTIPLE_CHOICE = 0,
  TRUE_FALSE = 1,
  SHORT_ANSWER = 2,
  MULTI_SELECT = 3,
  UNRECOGNIZED = -1,
}

export enum AttemptStatus {
  IN_PROGRESS = 0,
  SUBMITTED = 1,
  GRADED = 2,
  TIMED_OUT = 3,
  UNRECOGNIZED = -1,
}

export interface PageMeta {
  page: number;
  pageSize: number;
  count: number;
  pageCount?: number | undefined;
  hasPreviousPage?: boolean | undefined;
  hasNextPage?: boolean | undefined;
}

export interface QuestionOption {
  id: string;
  text: string;
  isCorrect: boolean;
  sortOrder: number;
}

export interface Question {
  id: string;
  quizId: string;
  type: QuestionType;
  text: string;
  explanation?: string | undefined;
  points: number;
  sortOrder: number;
  options: QuestionOption[];
  createdAt: string;
  updatedAt: string;
  pictureUrl?: string | undefined;
}

export interface Quiz {
  id: string;
  userId: string;
  title: string;
  description?: string | undefined;
  timeLimitSecs?: number | undefined;
  passingScore: number;
  maxAttempts: number;
  shuffleQuestions: boolean;
  isPublished: boolean;
  questionCount: number;
  questions: Question[];
  createdAt: string;
  updatedAt: string;
}

export interface CreateQuizRequest {
  userId: string;
  title: string;
  description?: string | undefined;
  timeLimitSecs?: number | undefined;
  passingScore?: number | undefined;
  maxAttempts?: number | undefined;
  shuffleQuestions?: boolean | undefined;
  questions: CreateQuestionInput[];
}

export interface CreateQuestionInput {
  type: QuestionType;
  text: string;
  explanation?: string | undefined;
  points?: number | undefined;
  sortOrder?: number | undefined;
  options: CreateOptionInput[];
  pictureUrl?: string | undefined;
}

export interface CreateOptionInput {
  text: string;
  isCorrect: boolean;
  sortOrder?: number | undefined;
}

export interface CreateQuizResponse {
  quiz?: Quiz | undefined;
}

export interface GetQuizByIdRequest {
  id: string;
}

export interface GetQuizByIdResponse {
  quiz?: Quiz | undefined;
}

export interface UpdateQuizRequest {
  id: string;
  title?: string | undefined;
  description?: string | undefined;
  timeLimitSecs?: number | undefined;
  passingScore?: number | undefined;
  maxAttempts?: number | undefined;
  shuffleQuestions?:
    | boolean
    | undefined;
  /** When true, set time_limit_secs to null */
  clearTimeLimit?: boolean | undefined;
}

export interface UpdateQuizResponse {
  quiz?: Quiz | undefined;
}

export interface DeleteQuizRequest {
  id: string;
}

export interface DeleteQuizResponse {
  message: string;
}

export interface GetAllQuizzesRequest {
  userId: string;
  page?: number | undefined;
  pageSize?: number | undefined;
  search?: string | undefined;
  sortBy?: string | undefined;
  order?: Order | undefined;
  isPublished?: boolean | undefined;
}

export interface GetAllQuizzesResponse {
  quizzes: Quiz[];
  meta?: PageMeta | undefined;
}

export interface PublishQuizRequest {
  id: string;
}

export interface PublishQuizResponse {
  quiz?: Quiz | undefined;
}

export interface UnpublishQuizRequest {
  id: string;
}

export interface UnpublishQuizResponse {
  quiz?: Quiz | undefined;
}

export interface AddQuestionRequest {
  quizId: string;
  type: QuestionType;
  text: string;
  explanation?: string | undefined;
  points?: number | undefined;
  sortOrder?: number | undefined;
  options: CreateOptionInput[];
  pictureUrl?: string | undefined;
}

export interface AddQuestionResponse {
  question?: Question | undefined;
}

export interface UpdateQuestionRequest {
  quizId: string;
  questionId: string;
  type?: QuestionType | undefined;
  text?: string | undefined;
  explanation?: string | undefined;
  points?: number | undefined;
  options: CreateOptionInput[];
  pictureUrl?: string | undefined;
}

export interface UpdateQuestionResponse {
  question?: Question | undefined;
}

export interface DeleteQuestionRequest {
  quizId: string;
  questionId: string;
}

export interface DeleteQuestionResponse {
  message: string;
}

export interface ReorderQuestionsRequest {
  quizId: string;
  questionIds: string[];
}

export interface ReorderQuestionsResponse {
  message: string;
}

export interface StartAttemptRequest {
  quizId: string;
  userId: string;
}

export interface StartAttemptResponse {
  attempt?: QuizAttempt | undefined;
  questions: AttemptQuestion[];
}

export interface AttemptQuestion {
  id: string;
  type: QuestionType;
  text: string;
  points: number;
  sortOrder: number;
  options: AttemptOption[];
}

export interface AttemptOption {
  id: string;
  text: string;
  sortOrder: number;
}

export interface SubmitAnswerRequest {
  attemptId: string;
  questionId: string;
  selectedOptionIds: string[];
  textAnswer?: string | undefined;
}

export interface SubmitAnswerResponse {
  message: string;
}

export interface SubmitAttemptRequest {
  attemptId: string;
}

export interface SubmitAttemptResponse {
  attempt?: QuizAttempt | undefined;
}

export interface QuizAttempt {
  id: string;
  quizId: string;
  userId: string;
  score?: number | undefined;
  totalPoints?: number | undefined;
  status: AttemptStatus;
  startedAt: string;
  submittedAt?: string | undefined;
}

export interface GetAttemptResultRequest {
  attemptId: string;
}

export interface AttemptAnswerResult {
  questionId: string;
  questionText: string;
  questionType: QuestionType;
  selectedOptionIds: string[];
  textAnswer?: string | undefined;
  isCorrect: boolean;
  pointsEarned: number;
  maxPoints: number;
  explanation?: string | undefined;
  correctOptions: QuestionOption[];
}

export interface GetAttemptResultResponse {
  attempt?: QuizAttempt | undefined;
  answers: AttemptAnswerResult[];
}

export interface GetAttemptHistoryRequest {
  quizId: string;
  userId?: string | undefined;
  page?: number | undefined;
  pageSize?: number | undefined;
}

export interface GetAttemptHistoryResponse {
  attempts: QuizAttempt[];
  meta?: PageMeta | undefined;
}

export interface QuestionStat {
  questionId: string;
  text: string;
  correctRate: number;
  averagePoints: number;
}

export interface GetQuizAnalyticsRequest {
  quizId: string;
}

export interface GetQuizAnalyticsResponse {
  quizId: string;
  totalAttempts: number;
  averageScore: number;
  passRate: number;
  questionStats: QuestionStat[];
}

export interface GetQuestionPictureUploadUrlRequest {
  quizId: string;
  questionId: string;
  filename: string;
  contentType: string;
}

export interface GetQuestionPictureUploadUrlResponse {
  uploadUrl: string;
  fields: { [key: string]: string };
  s3Key: string;
  publicUrl: string;
  expiresIn: number;
}

export interface GetQuestionPictureUploadUrlResponse_FieldsEntry {
  key: string;
  value: string;
}

export const QUIZSERVICE_PACKAGE_NAME = "quizservice";

export interface QuizServiceClient {
  /** Quiz CRUD */

  createQuiz(request: CreateQuizRequest): Observable<CreateQuizResponse>;

  getQuizById(request: GetQuizByIdRequest): Observable<GetQuizByIdResponse>;

  updateQuiz(request: UpdateQuizRequest): Observable<UpdateQuizResponse>;

  deleteQuiz(request: DeleteQuizRequest): Observable<DeleteQuizResponse>;

  getAllQuizzes(request: GetAllQuizzesRequest): Observable<GetAllQuizzesResponse>;

  publishQuiz(request: PublishQuizRequest): Observable<PublishQuizResponse>;

  unpublishQuiz(request: UnpublishQuizRequest): Observable<UnpublishQuizResponse>;

  /** Question management */

  addQuestion(request: AddQuestionRequest): Observable<AddQuestionResponse>;

  updateQuestion(request: UpdateQuestionRequest): Observable<UpdateQuestionResponse>;

  deleteQuestion(request: DeleteQuestionRequest): Observable<DeleteQuestionResponse>;

  reorderQuestions(request: ReorderQuestionsRequest): Observable<ReorderQuestionsResponse>;

  getQuestionPictureUploadUrl(
    request: GetQuestionPictureUploadUrlRequest,
  ): Observable<GetQuestionPictureUploadUrlResponse>;

  /** Quiz attempts */

  startAttempt(request: StartAttemptRequest): Observable<StartAttemptResponse>;

  submitAnswer(request: SubmitAnswerRequest): Observable<SubmitAnswerResponse>;

  submitAttempt(request: SubmitAttemptRequest): Observable<SubmitAttemptResponse>;

  getAttemptResult(request: GetAttemptResultRequest): Observable<GetAttemptResultResponse>;

  getAttemptHistory(request: GetAttemptHistoryRequest): Observable<GetAttemptHistoryResponse>;

  /** Analytics */

  getQuizAnalytics(request: GetQuizAnalyticsRequest): Observable<GetQuizAnalyticsResponse>;
}

export interface QuizServiceController {
  /** Quiz CRUD */

  createQuiz(
    request: CreateQuizRequest,
  ): Promise<CreateQuizResponse> | Observable<CreateQuizResponse> | CreateQuizResponse;

  getQuizById(
    request: GetQuizByIdRequest,
  ): Promise<GetQuizByIdResponse> | Observable<GetQuizByIdResponse> | GetQuizByIdResponse;

  updateQuiz(
    request: UpdateQuizRequest,
  ): Promise<UpdateQuizResponse> | Observable<UpdateQuizResponse> | UpdateQuizResponse;

  deleteQuiz(
    request: DeleteQuizRequest,
  ): Promise<DeleteQuizResponse> | Observable<DeleteQuizResponse> | DeleteQuizResponse;

  getAllQuizzes(
    request: GetAllQuizzesRequest,
  ): Promise<GetAllQuizzesResponse> | Observable<GetAllQuizzesResponse> | GetAllQuizzesResponse;

  publishQuiz(
    request: PublishQuizRequest,
  ): Promise<PublishQuizResponse> | Observable<PublishQuizResponse> | PublishQuizResponse;

  unpublishQuiz(
    request: UnpublishQuizRequest,
  ): Promise<UnpublishQuizResponse> | Observable<UnpublishQuizResponse> | UnpublishQuizResponse;

  /** Question management */

  addQuestion(
    request: AddQuestionRequest,
  ): Promise<AddQuestionResponse> | Observable<AddQuestionResponse> | AddQuestionResponse;

  updateQuestion(
    request: UpdateQuestionRequest,
  ): Promise<UpdateQuestionResponse> | Observable<UpdateQuestionResponse> | UpdateQuestionResponse;

  deleteQuestion(
    request: DeleteQuestionRequest,
  ): Promise<DeleteQuestionResponse> | Observable<DeleteQuestionResponse> | DeleteQuestionResponse;

  reorderQuestions(
    request: ReorderQuestionsRequest,
  ): Promise<ReorderQuestionsResponse> | Observable<ReorderQuestionsResponse> | ReorderQuestionsResponse;

  getQuestionPictureUploadUrl(
    request: GetQuestionPictureUploadUrlRequest,
  ):
    | Promise<GetQuestionPictureUploadUrlResponse>
    | Observable<GetQuestionPictureUploadUrlResponse>
    | GetQuestionPictureUploadUrlResponse;

  /** Quiz attempts */

  startAttempt(
    request: StartAttemptRequest,
  ): Promise<StartAttemptResponse> | Observable<StartAttemptResponse> | StartAttemptResponse;

  submitAnswer(
    request: SubmitAnswerRequest,
  ): Promise<SubmitAnswerResponse> | Observable<SubmitAnswerResponse> | SubmitAnswerResponse;

  submitAttempt(
    request: SubmitAttemptRequest,
  ): Promise<SubmitAttemptResponse> | Observable<SubmitAttemptResponse> | SubmitAttemptResponse;

  getAttemptResult(
    request: GetAttemptResultRequest,
  ): Promise<GetAttemptResultResponse> | Observable<GetAttemptResultResponse> | GetAttemptResultResponse;

  getAttemptHistory(
    request: GetAttemptHistoryRequest,
  ): Promise<GetAttemptHistoryResponse> | Observable<GetAttemptHistoryResponse> | GetAttemptHistoryResponse;

  /** Analytics */

  getQuizAnalytics(
    request: GetQuizAnalyticsRequest,
  ): Promise<GetQuizAnalyticsResponse> | Observable<GetQuizAnalyticsResponse> | GetQuizAnalyticsResponse;
}

export function QuizServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "createQuiz",
      "getQuizById",
      "updateQuiz",
      "deleteQuiz",
      "getAllQuizzes",
      "publishQuiz",
      "unpublishQuiz",
      "addQuestion",
      "updateQuestion",
      "deleteQuestion",
      "reorderQuestions",
      "getQuestionPictureUploadUrl",
      "startAttempt",
      "submitAnswer",
      "submitAttempt",
      "getAttemptResult",
      "getAttemptHistory",
      "getQuizAnalytics",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("QuizService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("QuizService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const QUIZ_SERVICE_NAME = "QuizService";
