// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v6.33.1
// source: proto/student-service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "studentservice";

export enum Order {
  ASC = 0,
  DESC = 1,
  UNRECOGNIZED = -1,
}

export interface PageMeta {
  page: number;
  pageSize: number;
  count: number;
  pageCount?: number | undefined;
  hasPreviousPage?: boolean | undefined;
  hasNextPage?: boolean | undefined;
}

export interface Filter {
  values: { [key: string]: string };
}

export interface Filter_ValuesEntry {
  key: string;
  value: string;
}

export interface User {
  id: string;
  username: string;
  email: string;
}

export interface StudentResponse {
  id: string;
  userId: string;
  username: string;
  firstName: string;
  lastName: string;
  address?: string | undefined;
  user: User | undefined;
  studentNumber?: string | undefined;
  phoneNumber?: string | undefined;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
}

export interface GetAllStudentsRequest {
  page?: number | undefined;
  pageSize?: number | undefined;
  order?: Order | undefined;
  skip?: number | undefined;
  filter?: Filter | undefined;
  sortBy?: string | undefined;
  query?: string | undefined;
  search?: string | undefined;
}

export interface GetAllStudentsResponse {
  data: StudentResponse[];
  meta: PageMeta | undefined;
}

export interface GetStudentByIdRequest {
  id: string;
}

export interface GetStudentByUserIdRequest {
  userId: string;
}

export interface UpdateStudentByIdRequest {
  id: string;
  username?: string | undefined;
  firstName?: string | undefined;
  lastName?: string | undefined;
  address?: string | undefined;
  phoneNumber?: string | undefined;
  email?: string | undefined;
}

export interface DeleteStudentByIdRequest {
  id: string;
}

export interface DeleteStudentByIdResponse {
  message: string;
}

export const STUDENTSERVICE_PACKAGE_NAME = "studentservice";

export interface StudentServiceClient {
  findAllStudents(request: GetAllStudentsRequest): Observable<GetAllStudentsResponse>;

  findStudentById(request: GetStudentByIdRequest): Observable<StudentResponse>;

  findStudentByUserId(request: GetStudentByUserIdRequest): Observable<StudentResponse>;

  updateStudentById(request: UpdateStudentByIdRequest): Observable<StudentResponse>;

  deleteStudentById(request: DeleteStudentByIdRequest): Observable<DeleteStudentByIdResponse>;
}

export interface StudentServiceController {
  findAllStudents(
    request: GetAllStudentsRequest,
  ): Promise<GetAllStudentsResponse> | Observable<GetAllStudentsResponse> | GetAllStudentsResponse;

  findStudentById(
    request: GetStudentByIdRequest,
  ): Promise<StudentResponse> | Observable<StudentResponse> | StudentResponse;

  findStudentByUserId(
    request: GetStudentByUserIdRequest,
  ): Promise<StudentResponse> | Observable<StudentResponse> | StudentResponse;

  updateStudentById(
    request: UpdateStudentByIdRequest,
  ): Promise<StudentResponse> | Observable<StudentResponse> | StudentResponse;

  deleteStudentById(
    request: DeleteStudentByIdRequest,
  ): Promise<DeleteStudentByIdResponse> | Observable<DeleteStudentByIdResponse> | DeleteStudentByIdResponse;
}

export function StudentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "findAllStudents",
      "findStudentById",
      "findStudentByUserId",
      "updateStudentById",
      "deleteStudentById",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("StudentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("StudentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const STUDENT_SERVICE_NAME = "StudentService";
