// Code generated by protoc-gen-ts_proto. DO NOT EDIT.
// versions:
//   protoc-gen-ts_proto  v2.8.3
//   protoc               v7.34.0
// source: proto/student-service.proto

/* eslint-disable */
import { GrpcMethod, GrpcStreamMethod } from "@nestjs/microservices";
import { Observable } from "rxjs";

export const protobufPackage = "studentservice";

export enum Order {
  ASC = 0,
  DESC = 1,
  UNRECOGNIZED = -1,
}

export enum AssignmentStatus {
  ASSIGNED = 0,
  IN_PROGRESS = 1,
  COMPLETED = 2,
  OVERDUE = 3,
  UNRECOGNIZED = -1,
}

export enum ProgressAction {
  COMPLETE_SECTION = 0,
  ANSWER_QUESTION = 1,
  UNRECOGNIZED = -1,
}

export interface PageMeta {
  page: number;
  pageSize: number;
  count: number;
  pageCount?: number | undefined;
  hasPreviousPage?: boolean | undefined;
  hasNextPage?: boolean | undefined;
}

export interface User {
  id: string;
  username: string;
  email: string;
}

export interface Student {
  id: string;
  userId: string;
  uniqueId: string;
  fullName: string;
  phoneNumber?: string | undefined;
  dateOfBirth?: string | undefined;
  profilePictureUrl?: string | undefined;
  bio?: string | undefined;
  branchId?: string | undefined;
  branchName?: string | undefined;
  active: string;
  createdAt: string;
  updatedAt: string;
  deletedAt?: string | undefined;
  user?: User | undefined;
}

export interface RegisterStudentRequest {
  userId: string;
  fullName: string;
  branchId: string;
  phoneNumber?: string | undefined;
  dateOfBirth?: string | undefined;
  profilePictureUrl?: string | undefined;
  bio?: string | undefined;
}

export interface RegisterStudentResponse {
  student?: Student | undefined;
}

export interface GetStudentByIdRequest {
  id: string;
}

export interface GetStudentByIdResponse {
  student?: Student | undefined;
}

export interface GetStudentByUserIdRequest {
  userId: string;
}

export interface GetStudentByUserIdResponse {
  student?: Student | undefined;
}

export interface UpdateStudentRequest {
  id: string;
  fullName?: string | undefined;
  phoneNumber?: string | undefined;
  dateOfBirth?: string | undefined;
  bio?: string | undefined;
}

export interface UpdateStudentResponse {
  student?: Student | undefined;
}

export interface DeleteStudentRequest {
  id: string;
}

export interface DeleteStudentResponse {
  message: string;
}

export interface GetAllStudentsRequest {
  page?: number | undefined;
  pageSize?: number | undefined;
  search?: string | undefined;
  sortBy?: string | undefined;
  order?: Order | undefined;
}

export interface GetAllStudentsResponse {
  students: Student[];
  meta?: PageMeta | undefined;
}

export interface Assignment {
  id: string;
  teacherId: string;
  studentId: string;
  contentId: string;
  status: AssignmentStatus;
  progress: number;
  dueDate?: string | undefined;
  assignedAt: string;
  startedAt?: string | undefined;
  completedAt?: string | undefined;
  student?: Student | undefined;
  createdAt: string;
  updatedAt: string;
}

export interface CreateAssignmentRequest {
  teacherId: string;
  studentId: string;
  contentId: string;
  dueDate?: string | undefined;
}

export interface CreateAssignmentResponse {
  assignment?: Assignment | undefined;
}

export interface BulkCreateAssignmentsRequest {
  teacherId: string;
  studentIds: string[];
  contentId: string;
  dueDate?: string | undefined;
}

export interface BulkCreateAssignmentsResponse {
  assignments: Assignment[];
  created: number;
  skipped: number;
}

export interface DeleteAssignmentRequest {
  teacherId: string;
  studentId: string;
  contentId: string;
}

export interface DeleteAssignmentResponse {
  message: string;
}

export interface GetAssignmentRequest {
  studentId: string;
  contentId: string;
}

export interface GetAssignmentResponse {
  assignment?: Assignment | undefined;
}

export interface GetStudentAssignmentsRequest {
  studentId: string;
  status?: AssignmentStatus | undefined;
  page?: number | undefined;
  pageSize?: number | undefined;
}

export interface GetStudentAssignmentsResponse {
  assignments: Assignment[];
  meta?: PageMeta | undefined;
}

export interface GetTeacherAssignmentsRequest {
  teacherId: string;
  contentId?: string | undefined;
  status?: AssignmentStatus | undefined;
  page?: number | undefined;
  pageSize?: number | undefined;
}

export interface GetTeacherAssignmentsResponse {
  assignments: Assignment[];
  meta?: PageMeta | undefined;
}

export interface GetContentAssignmentsRequest {
  contentId: string;
  page?: number | undefined;
  pageSize?: number | undefined;
}

export interface GetContentAssignmentsResponse {
  assignments: Assignment[];
  meta?: PageMeta | undefined;
  totalAssigned: number;
}

export interface UpdateProgressRequest {
  studentId: string;
  contentId: string;
  action: ProgressAction;
  sectionId?: string | undefined;
  questionId?: string | undefined;
}

export interface UpdateProgressResponse {
  assignment?: Assignment | undefined;
  alreadyLogged: boolean;
}

export interface GetProgressLogsRequest {
  assignmentId: string;
}

export interface ProgressLog {
  id: string;
  assignmentId: string;
  sectionId?: string | undefined;
  questionId?: string | undefined;
  action: ProgressAction;
  createdAt: string;
}

export interface GetProgressLogsResponse {
  logs: ProgressLog[];
  progress: number;
  completedItems: number;
  totalItems: number;
}

export interface ProfilePictureUploadUrlRequest {
  filename: string;
  contentType: string;
}

export interface ProfilePictureUploadUrlResponse {
  uploadUrl: string;
  fields: { [key: string]: string };
  s3Key: string;
  publicUrl: string;
  expiresIn: number;
}

export interface ProfilePictureUploadUrlResponse_FieldsEntry {
  key: string;
  value: string;
}

export const STUDENTSERVICE_PACKAGE_NAME = "studentservice";

export interface StudentServiceClient {
  /** Student CRUD */

  registerStudent(request: RegisterStudentRequest): Observable<RegisterStudentResponse>;

  getStudentById(request: GetStudentByIdRequest): Observable<GetStudentByIdResponse>;

  getStudentByUserId(request: GetStudentByUserIdRequest): Observable<GetStudentByUserIdResponse>;

  updateStudent(request: UpdateStudentRequest): Observable<UpdateStudentResponse>;

  deleteStudent(request: DeleteStudentRequest): Observable<DeleteStudentResponse>;

  getAllStudents(request: GetAllStudentsRequest): Observable<GetAllStudentsResponse>;

  getProfilePictureUploadUrl(request: ProfilePictureUploadUrlRequest): Observable<ProfilePictureUploadUrlResponse>;

  /** Assignment management */

  createAssignment(request: CreateAssignmentRequest): Observable<CreateAssignmentResponse>;

  bulkCreateAssignments(request: BulkCreateAssignmentsRequest): Observable<BulkCreateAssignmentsResponse>;

  deleteAssignment(request: DeleteAssignmentRequest): Observable<DeleteAssignmentResponse>;

  getAssignment(request: GetAssignmentRequest): Observable<GetAssignmentResponse>;

  /** Query assignments */

  getStudentAssignments(request: GetStudentAssignmentsRequest): Observable<GetStudentAssignmentsResponse>;

  getTeacherAssignments(request: GetTeacherAssignmentsRequest): Observable<GetTeacherAssignmentsResponse>;

  getContentAssignments(request: GetContentAssignmentsRequest): Observable<GetContentAssignmentsResponse>;

  /** Progress tracking */

  updateProgress(request: UpdateProgressRequest): Observable<UpdateProgressResponse>;

  getProgressLogs(request: GetProgressLogsRequest): Observable<GetProgressLogsResponse>;
}

export interface StudentServiceController {
  /** Student CRUD */

  registerStudent(
    request: RegisterStudentRequest,
  ): Promise<RegisterStudentResponse> | Observable<RegisterStudentResponse> | RegisterStudentResponse;

  getStudentById(
    request: GetStudentByIdRequest,
  ): Promise<GetStudentByIdResponse> | Observable<GetStudentByIdResponse> | GetStudentByIdResponse;

  getStudentByUserId(
    request: GetStudentByUserIdRequest,
  ): Promise<GetStudentByUserIdResponse> | Observable<GetStudentByUserIdResponse> | GetStudentByUserIdResponse;

  updateStudent(
    request: UpdateStudentRequest,
  ): Promise<UpdateStudentResponse> | Observable<UpdateStudentResponse> | UpdateStudentResponse;

  deleteStudent(
    request: DeleteStudentRequest,
  ): Promise<DeleteStudentResponse> | Observable<DeleteStudentResponse> | DeleteStudentResponse;

  getAllStudents(
    request: GetAllStudentsRequest,
  ): Promise<GetAllStudentsResponse> | Observable<GetAllStudentsResponse> | GetAllStudentsResponse;

  getProfilePictureUploadUrl(
    request: ProfilePictureUploadUrlRequest,
  ):
    | Promise<ProfilePictureUploadUrlResponse>
    | Observable<ProfilePictureUploadUrlResponse>
    | ProfilePictureUploadUrlResponse;

  /** Assignment management */

  createAssignment(
    request: CreateAssignmentRequest,
  ): Promise<CreateAssignmentResponse> | Observable<CreateAssignmentResponse> | CreateAssignmentResponse;

  bulkCreateAssignments(
    request: BulkCreateAssignmentsRequest,
  ): Promise<BulkCreateAssignmentsResponse> | Observable<BulkCreateAssignmentsResponse> | BulkCreateAssignmentsResponse;

  deleteAssignment(
    request: DeleteAssignmentRequest,
  ): Promise<DeleteAssignmentResponse> | Observable<DeleteAssignmentResponse> | DeleteAssignmentResponse;

  getAssignment(
    request: GetAssignmentRequest,
  ): Promise<GetAssignmentResponse> | Observable<GetAssignmentResponse> | GetAssignmentResponse;

  /** Query assignments */

  getStudentAssignments(
    request: GetStudentAssignmentsRequest,
  ): Promise<GetStudentAssignmentsResponse> | Observable<GetStudentAssignmentsResponse> | GetStudentAssignmentsResponse;

  getTeacherAssignments(
    request: GetTeacherAssignmentsRequest,
  ): Promise<GetTeacherAssignmentsResponse> | Observable<GetTeacherAssignmentsResponse> | GetTeacherAssignmentsResponse;

  getContentAssignments(
    request: GetContentAssignmentsRequest,
  ): Promise<GetContentAssignmentsResponse> | Observable<GetContentAssignmentsResponse> | GetContentAssignmentsResponse;

  /** Progress tracking */

  updateProgress(
    request: UpdateProgressRequest,
  ): Promise<UpdateProgressResponse> | Observable<UpdateProgressResponse> | UpdateProgressResponse;

  getProgressLogs(
    request: GetProgressLogsRequest,
  ): Promise<GetProgressLogsResponse> | Observable<GetProgressLogsResponse> | GetProgressLogsResponse;
}

export function StudentServiceControllerMethods() {
  return function (constructor: Function) {
    const grpcMethods: string[] = [
      "registerStudent",
      "getStudentById",
      "getStudentByUserId",
      "updateStudent",
      "deleteStudent",
      "getAllStudents",
      "getProfilePictureUploadUrl",
      "createAssignment",
      "bulkCreateAssignments",
      "deleteAssignment",
      "getAssignment",
      "getStudentAssignments",
      "getTeacherAssignments",
      "getContentAssignments",
      "updateProgress",
      "getProgressLogs",
    ];
    for (const method of grpcMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcMethod("StudentService", method)(constructor.prototype[method], method, descriptor);
    }
    const grpcStreamMethods: string[] = [];
    for (const method of grpcStreamMethods) {
      const descriptor: any = Reflect.getOwnPropertyDescriptor(constructor.prototype, method);
      GrpcStreamMethod("StudentService", method)(constructor.prototype[method], method, descriptor);
    }
  };
}

export const STUDENT_SERVICE_NAME = "StudentService";
